services:
  - type: web
    name: clima-weather
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clima-db
          property: connectionString
      - key: RAILS_ENV
        value: production
databases:
  - name: clima-db
