services:
  - type: web
    name: clima-app
    env: ruby
    plan: free
    buildCommand: "bundle install && yarn install --check-files || true"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
